<?php

declare(strict_types=1);

namespace PluginName;

use PluginName\Vendor\Codex\Application;

/**
 * Load dependencies using the Composer autoloader.
 *
 * This allows us to load third-party libraries without having to include
 * or require the files from the libraries manually.
 *
 * This file is generated by PHP-Scoper ({@link https://github.com/humbug/php-scoper}),
 * a Composer plugin that scopes the namespaces of third-party libraries. It
 * prevents conflicts with other plugins or themes that might use the same
 * libraries or packages with the same namespaces or class names.
 *
 * @see https://getcomposer.org/doc/01-basic-usage.md#autoloading
 * @see https://deliciousbrains.com/php-scoper-namespace-composer-dependencies/
 */
require PLUGIN_DIR . '/dist-autoload/vendor/scoper-autoload.php';

/**
 * Initialize the plugin application.
 */
$app = new Application(new Plugin());
$app->setPluginFilePath(PLUGIN_FILE);
$app->addServices(include plugin_dir_path('/inc/bootstrap/providers.php'));
$app->boot();
